# Generated by Django 3.0.8 on 2020-07-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=500)),
                ('table_name', models.CharField(max_length=500)),
                ('server_url', models.CharField(max_length=500)),
                ('port_number', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
