# Generated by Django 3.0.8 on 2020-07-08 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source_database',
            old_name='date',
            new_name='date_created',
        ),
    ]
