# Generated by Django 3.0.8 on 2020-07-08 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source_db', '0002_auto_20200708_0851'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Source_DataBase',
            new_name='SourceDatabase',
        ),
    ]
