# Generated by Django 3.0.8 on 2020-07-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_db', '0003_auto_20200708_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcedatabase',
            name='database_id',
            field=models.IntegerField(default=0),
        ),
    ]
