# Generated by Django 3.0.8 on 2020-07-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source_db', '0005_targetdatabase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TargetDatabase',
        ),
    ]
