# Generated by Django 3.0.8 on 2020-07-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source_db', '0006_delete_targetdatabase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcedatabase',
            name='date_created',
        ),
    ]
